name: MyPortal
services:
  my-portal-builder:
    build:
      context: ./frontend/my-portal
    image: my-portal-builder:latest
    container_name: my-portal-builder
    volumes:
      - portal-build:/usr/share/nginx/my-portal
    command: sh -c "npm install && npm run build && sleep infinity"
  
  bbs-builder:
    build:
      context: ./frontend/bbs
      dockerfile: Dockerfile
    image: bbs-builder:latest
    container_name: bbs-builder
    volumes:
      - bbs-build:/usr/share/nginx/bbs
    command: sh -c "npm install && npm run build && rm -rf /usr/share/nginx/bbs/* && cp -r /app/dist/* /usr/share/nginx/bbs/ && sleep infinity"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - portal-build:/usr/share/nginx/my-portal
      - bbs-build:/usr/share/nginx/bbs
    depends_on:
      - my-portal-builder
      - bbs-builder

volumes:
  portal-build:
  bbs-build: