version: '3.8'
name: MyPortal

services:
  my-portal-builder:
    build:
      context: ./frontend/my-portal
    image: my-portal-builder:latest
    container_name: my-portal-builder
    volumes:
      - portal-build:/usr/share/nginx/my-portal 
    command: sh -c "cd /app && npm install && rm -rf /usr/share/nginx/my-portal/* && npm run build && cp -r build/* /usr/share/nginx/my-portal && chmod -R 755 /usr/share/nginx/my-portal"

  bbs-builder:
    build:
      context: ./frontend/bbs
      dockerfile: Dockerfile
    image: bbs-builder:latest
    container_name: bbs-builder
    volumes:
      - bbs-build:/usr/share/nginx/bbs
    command: sh -c "cd /app && npm install && rm -rf /usr/share/nginx/bbs/* && npm run build && cp -r dist/* /usr/share/nginx/bbs && chmod -R 755 /usr/share/nginx/bbs"
 
  sample-builder:
    build:
      context: ./frontend/sample
      dockerfile: Dockerfile
    image: sample-builder:latest
    container_name: sample-builder
    volumes:
      - sample-build:/usr/share/nginx/sample
    command: sh -c "cd /app && npm install && rm -rf /usr/share/nginx/sample/* && npm run build && cp -r dist/* /usr/share/nginx/sample && chmod -R 755 /usr/share/nginx/sample"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - portal-build:/usr/share/nginx/my-portal:ro
      - bbs-build:/usr/share/nginx/bbs:ro
      - sample-build:/usr/share/nginx/sample:ro
    depends_on:
      - my-portal-builder
      - bbs-builder
      - sample-builder

volumes:
  portal-build:
  bbs-build:
  sample-build: