services:
  vite-builder:
    container_name: vite-builder
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/dist:/app/dist
    command:  sh -c "cd /app && npm install && rm -rf /usr/share/nginx/html/* && npm run build && cp -r data/dist/* /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./data/dist:/usr/share/nginx/html:ro
      # カスタムNginx設定ファイルのマウント
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vite-builder
    restart: always